export { default as Resource1 } from './resource1.png'
export { default as Resource2 } from './resource2.png'
export { default as Resource3 } from './resource3.png'
export { default as Resource4 } from './resource4.png'
export { default as GithubRepo } from './github-repo.png'
